ALTER TABLE dbo.orderevent ADD CONSTRAINT
	PK_orderevent PRIMARY KEY CLUSTERED 
	(
	id_orderevent
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

