ALTER TABLE dbo.inventorybody ADD CONSTRAINT
	PK_inventorybody PRIMARY KEY CLUSTERED 
	(
	id_inventorybody
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
