ALTER TABLE dbo.verificationbody ADD CONSTRAINT
	PK_verificationbody PRIMARY KEY CLUSTERED 
	(
	id_verificationbody
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
