CREATE NONCLUSTERED INDEX IX_order_2 ON dbo.[order]
	(
	input_date,
	status
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
