CREATE NONCLUSTERED INDEX IX_verificationbody ON dbo.verificationbody
	(
	id_verification
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
