CREATE NONCLUSTERED INDEX IX_inventorybody_1 ON dbo.inventorybody
	(
	order_number
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
