CREATE NONCLUSTERED INDEX IX_inventorybody ON dbo.inventorybody
	(
	id_inventory
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
