<?php
include("config.inc");
$dbh = ibase_connect(DB, DBUSER, DBPASSWD ,"win1251");

$k = $_GET["k"];
if ($k == "") $k = 0;
$o = $_GET["o"];
if ($o == "") $o = 0;
$KIOSKID = $k;
$ORDERNUMBER = $o;

$s .= "<?xml version=\"1.0\" encoding=\"windows-1251\"?>\n<KORDER>\n";

$query = <<<EOD
			SELECT 
				KIOSK_ORDERS.KID AS NUMBER,
				KIOSK_ORDERS.SESSIONID AS KIOSKID,
				KIOSKS.ADDRESS,
				KIOSK_ORDERS.STAMP,
				KIOSK_ORDERS.CUSTOMER,
				KIOSK_ORDERS.PHONE,
				AUTH.USERNAME AS TOPRINT_AUTHID,
				KIOSK_ORDERS.TOPRINT_AUTHDATE,
				AUTH1.USERNAME AS PRINTED_AUTHID,
				KIOSK_ORDERS.PRINTED_AUTHDATE,
				KIOSK_ORDERS.SHIP_AUTHID,
				KIOSK_ORDERS.SHIP_AUTHDATE,
				KIOSK_ORDERS.STATUS,
				KIOSK_ORDERS.CARDID,
				KIOSK_ORDERS.PRINTER_ADDRESS
			FROM
				KIOSK_ORDERS
				INNER JOIN KIOSKS ON (KIOSK_ORDERS.SESSIONID = KIOSKS.ID)
				LEFT OUTER JOIN AUTH ON (KIOSK_ORDERS.TOPRINT_AUTHID = AUTH.ID)
				LEFT OUTER JOIN AUTH AUTH1 ON (KIOSK_ORDERS.PRINTED_AUTHID = AUTH1.ID)
			WHERE
				(KIOSK_ORDERS.KID = $ORDERNUMBER) AND 
				(KIOSK_ORDERS.SESSIONID = $KIOSKID)
EOD;

$h = ibase_query($dbh, $query);
while ($row = ibase_fetch_object($h))
{
	$op = $row->PRINTED_AUTHID;
	if($op == "")
		$op == "no_data";
	$s .= <<<EOD
	<HEADER>
		<NUMBER>$row->NUMBER</NUMBER>
		<KIOSKID>$row->KIOSKID</KIOSKID>
		<ADDRESS>$row->ADDRESS</ADDRESS>
		<STAMP>$row->STAMP</STAMP>
		<CUSTOMER>$row->CUSTOMER</CUSTOMER>
		<PHONE>$row->PHONE</PHONE>
		<TOPRINT_AUTHID>$row->TOPRINT_AUTHID</TOPRINT_AUTHID>
		<TOPRINT_AUTHDATE>$row->TOPRINT_AUTHDATE</TOPRINT_AUTHDATE>
		<PRINTED_AUTHID>$op</PRINTED_AUTHID>
		<PRINTED_AUTHDATE>$row->PRINTED_AUTHDATE</PRINTED_AUTHDATE>
		<SHIP_AUTHID>$row->SHIP_AUTHID</SHIP_AUTHID>
		<SHIP_AUTHDATE>$row->SHIP_AUTHDATE</SHIP_AUTHDATE>
		<STATUS>$row->STATUS</STATUS>
		<CARDID>$row->CARDID</CARDID>
		<PRINTER_ADDRESS>$row->PRINTER_ADDRESS</PRINTER_ADDRESS>
	</HEADER>

EOD;
};
ibase_free_result($h);

$query = <<<EOD
			SELECT 
				D.ACTION_ID,
				P1.ACTION_NAME,
				PH.HEADER,
				P1.PRICE,
				D.SUBACTION_ID,
				P.ACTION_NAME,
				P.PRICE,
				SUM(D.QTY) AS QTY,
				D.PRICE,
				D.SID,
				D.KID
			FROM
				KIOSK_ORDER_DETAIL D
				LEFT OUTER JOIN PRICE_LISTS P ON (D.SUBACTION_ID = P.ID)
				INNER JOIN PRICE_LISTS P1 ON (D.ACTION_ID = P1.ID)
				INNER JOIN PRICEHEADER PH ON (P1.HID = PH.ID)
			WHERE
				KID = $KIOSKID AND 
				SID = $ORDERNUMBER AND 
				P1.GID = (SELECT KIOSK_PRICE.PRICE_GROUP FROM KIOSK_PRICE WHERE KIOSK_PRICE.KIOSK_ID = $KIOSKID) AND 
				P.GID = (SELECT KIOSK_PRICE.PRICE_GROUP FROM KIOSK_PRICE WHERE KIOSK_PRICE.KIOSK_ID = $KIOSKID)
			GROUP BY
				D.ACTION_ID,
				P1.ACTION_NAME,
				PH.HEADER,
				P1.PRICE,
				D.SUBACTION_ID,
				P.ACTION_NAME,
				P.PRICE,
				D.PRICE,
				D.SID,
				D.KID
EOD;
$h = ibase_query($dbh, $query);

$s .= "\t<BODY>\n";
while ($row = ibase_fetch_object($h))
{
	$s .= <<<EOD
		<ROW>
			<ACTION_ID>$row->ACTION_ID</ACTION_ID>
			<ACTION_NAME>$row->ACTION_NAME</ACTION_NAME>
			<ACTION_HEADER>$row->ACTION_HEADER</ACTION_HEADER>
			<ACTION_PRICE>$row->ACTION_PRICE</ACTION_PRICE>
			<SUBACTION_ID>$row->SUBACTION_ID</SUBACTION_ID>
			<SUBACTION_NAME>$row->SUBACTION_NAME</SUBACTION_NAME>
			<SUBACTION_PRICE>$row->SUBACTION_PRICE</SUBACTION_PRICE>
			<QTY>$row->QTY</QTY>
			<PRICE>$row->PRICE</PRICE>
			<SID>$row->SID</SID>
			<KID>$row->KID</KID>
		</ROW>

EOD;
};
ibase_free_result($h);
$s .= "\t</BODY>\n";

$s .= "</KORDER>\n";
echo $s;

ibase_close($dbh);
?>